global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'routeServiceStateChangeCounter'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s 			
    static_configs:
      - targets: ['localhost:8080']
