spring: 
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      
  h2:
    console:
      enabled: true
      path: /h2-console
      
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE 
    platform: h2
    
# The sample supports two profile nonReactive and reactive OAuth2/JWT Security
  profiles:
    active: nonReactive

  security:
    oauth2:
      resourceserver:
        jwt: 
          public-key-location: public-key.txt
          
  